#!/usr/bin/python3

import urllib.request, json, requests


#resp = requests.get(url="http://www.talon.kiachma.webfactional.com/weather/ENTO")
#weather = json.loads(resp.text)
headers = {'Authorization':'zxkqGwCwZjMOIzqTpq0gcZCUf4gw4qQiH-K0PZQqOIo'}
resp = requests.get(url="https://avwx.rest/api/metar/ENGM",headers=headers)
weather = json.loads(resp.text)
#cond = json.loads(resp.text)
#metar = weather["aviationProducts"]["meteorologicalAerodromeReport"][-1]["metarText"]
metar = weather["raw"]
#if cond == "Standby":
print( (metar))
#elif cond == "Unrestricted":
#	print("%%{F#99cc99}%s" % (metar))
#else:
#	print("%%{F#ffcc66}%s : %s" % (cond,metar))



