#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}



hc emit_hook reload

xsetroot -solid '#5A8E3A'


# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close_or_remove 
hc keybind $Mod-Return spawn xterm


hc keybind $Mod-q spawn firefox
hc keybind $Mod-t spawn chromium --app="https://mail.google.com"
hc keybind $Mod-p spawn dmenu-launch
hc keybind $Mod-s spawn subl3
hc keybind $Mod-d spawn thunar
hc keybind $Mod-v spawn slock
hc keybind $Mod-w spawn chromium --app="https://www.google.com/calendar/"
hc keybind $Mod-Control-f floating toggle
hc keybind $Mod-e spawn spotify &

# tags
TAG_NAMES=( web term dev files doc mail media soc random float )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
#hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
#hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# look

hc set frame_border_active_color '#ff00a0'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#dddddd'
hc set frame_bg_active_color '#ccff00'
hc set frame_border_width 1
hc set window_border_width 1
hc set window_border_inner_width 0
hc set window_border_normal_color '#1c1c1c'
hc set window_border_active_color '#ccff00'
hc set always_show_frame 1
hc set frame_gap 0

# add overlapping window borders
hc set window_gap 1
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# transparency is needed for useless gaps
hc set frame_bg_transparent 1

hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

hc rule class=feh manage=off

# Set wallpaper
feh --bg-scale /home/eaura/Google\ Drive/wallpaper.jpg 

# Touchpad off
#synclient TouchpadOff=$(synclient -l | grep -c 'TouchpadOff.*=.*0')

# unlock, just to be sure
hc unlock

redshift &
herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:

#hc set_monitors 1366x768+0+0 1920x1080+1366+0
#hc set_monitors 1920x1200+0+0 1600x900+0+1200
# or simply:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done

## floating windows handling:
#https://reddit.com/r/unixporn/comments/1l1eaa/archherbstluftwm_single_floating_windowspopups/
#create a virtual monitor for floating windows
#a=$(herbstclient list_monitors | grep two)
#if [ "$a" == "" ]; then
#	hc floating float on

#	hc add_monitor 1027x768 float two
	
#	hc lock_tag two
#fi
